### ISSUE TITLE
Handling invalid tlds

### ISSUE THREAD

**Issue by MattHeslington** [131/node-tld#13]
Hello,

Great library!  

What's the recommended way of handling errors caused by invalid TLDs, please?

**Comment by mfpopa** [comment]
@MattHeslington Can you please describe a bit more regarding what you consider an "invalid" TLD? Is it a TLD that actually does not exist in reality? Is it just a TLD that is not in the list provided by this library?

Generally, the answer depends on how you're using the output of the `parse_url` function. Maybe the `allowUnknownTLD` option is what you are looking for since it will accept any type of URL, even something like `https://127.0.0.1:8000/path/to/something` without throwing an error, but the output (tld, domain and sub) may not be what you need or you'll have to process it yourself based on your requriements.
